
#user  nginx;
worker_processes  1;

#error_log  /var/log/nginx/error.log warn;
error_log  /var/log/nginx/error.log info;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    # BGE default.conf nicht mehr einbinden
    #include /etc/nginx/conf.d/*.conf;


    # BGE Bei Verwendung von upstream muss der benannte Dienst vorhanden sein, demnach könnte dieser Container
    # nur innerhalb von docker-compose verwendet werden.
    upstream destination-spritpreisradar-backend {
        server spritpreisradar-backend-service:60111;
    }

    # Taken from https://github.com/angular/angular/issues/18306
    server {
        listen       80;
        listen       443;
        server_name  localhost;
        location / {
            # Hier liegt die Angular App.
            root      /usr/share/nginx/html;
            index     index.html;
            # Siehe https://angular.io/guide/deployment#routed-apps-must-fall-back-to-indexhtml
            # If the application uses the Angular router, you must configure the server to return the application's host page (index.html) when asked for a file that it does not have.
            try_files $uri $uri/ /index.html?$args;
        }

        location /api/ {
            proxy_pass http://destination-spritpreisradar-backend;
            #proxy_pass http://portal-backend:60111;
            #proxy_http_version 1.1;
            #proxy_set_header Upgrade $http_upgrade;
            #proxy_set_header Connection 'upgrade';
            #proxy_set_header Host $host;
            #proxy_cache_bypass $http_upgrade;
            #rewrite ^/api(.*)$ $1 break;
        }

        # BGE 19.02.2024 Swagger Dokumentation wird automatisch vom Backend bereitgestellt
        location /docs/ {
            proxy_pass http://destination-spritpreisradar-backend;
            #proxy_pass http://portal-backend:60111;
        }
    }
}
