drop schema if exists mdm cascade;

CREATE SCHEMA IF NOT EXISTS MDM;

/* Tabelle FUELPRICE */

CREATE TABLE MDM.FUELPRICE (
  ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  STATIONID VARCHAR(40),
  E5 NUMERIC(7,3),
  E10 NUMERIC(7,3),
  DIESEL NUMERIC(7,3),
  VALIDFROM TIMESTAMP,
  VALIDUNTIL TIMESTAMP,
  FIRSTDATE TIMESTAMP,
  LASTDATE TIMESTAMP,
  IMPORTFILE VARCHAR(255));

CREATE INDEX IX_FUELPRICE_1 ON MDM.FuelPrice (StationId, ValidUntil);
CREATE INDEX IX_FUELPRICE_2 ON MDM.FuelPrice (ValidUntil,ValidFrom);
CREATE INDEX IX_FUELPRICE_3 ON MDM.FuelPrice (date_trunc('day', ValidFrom), date_trunc('day', ValidUntil));
CREATE INDEX IX_FUELPRICE_4 ON MDM.FuelPrice (stationid, e5, e10, diesel);
CREATE INDEX IX_FUELPRICE_5 ON MDM.FuelPrice (date_trunc('day', LastDate), VALIDUNTIL);


/* Tabelle STATION */

CREATE TABLE MDM.STATION (
  STATIONID VARCHAR(40),
  NAME VARCHAR(255),
  BRAND VARCHAR(255),
  STREET VARCHAR(255),
  STREETN VARCHAR(255),
  HOUSENUMBER VARCHAR(40),
  POSTCODE VARCHAR(20),
  PLACE VARCHAR(255),
  PLACEN VARCHAR(255),
  LATITUDE NUMERIC,
  LONGITUDE NUMERIC,
  OPENINGTIMES VARCHAR(1000),
  VERSION INTEGER,
  VALIDFROM TIMESTAMP,
  VALIDUNTIL TIMESTAMP,
  LASTDATE TIMESTAMP,
  IMPORTFILE VARCHAR(255));

CREATE INDEX IX_STATION_1 ON MDM.STATION(STATIONID, VALIDUNTIL);
CREATE INDEX IX_STATION_2 ON MDM.STATION (STATIONID,UPPER(Brand),ValidUntil,ValidFrom);
CREATE INDEX IX_STATION_3 ON MDM.STATION (STATIONID,PLACEN,ValidUntil,ValidFrom);
CREATE INDEX IX_STATION_4 ON MDM.STATION (STATIONID,POSTCODE,ValidUntil,ValidFrom);
CREATE INDEX IX_STATION_5 ON MDM.STATION (LATITUDE, LONGITUDE, VALIDUNTIL );
CREATE INDEX IX_STATION_6 ON MDM.STATION(POSTCODE) ;
CREATE INDEX IX_STATION_7 ON MDM.STATION(PLACEN) ;


/* Tabelle STATIONID */

CREATE TABLE MDM.STATIONID (
  ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  STATIONID VARCHAR(40),
  FIRSTDATE TIMESTAMP DEFAULT NOW());

CREATE INDEX IX_STATIONID_1 on MDM.StationID(StationID, ID);


/* Tabelle OPENINGTIMES */

CREATE TABLE MDM.OPENINGTIMES (
  STATIONID VARCHAR(40) NOT NULL,
  DAY NUMERIC NOT NULL,
  STARTTIME VARCHAR(40) NOT NULL,
  ENDTIME VARCHAR(40) NOT NULL);

CREATE INDEX IX_OPENINGTIMES_1 ON MDM.OPENINGTIMES (StationId);
CREATE UNIQUE INDEX IX_OPENINGTIMES_2 ON MDM.OPENINGTIMES (StationId, DAY, STARTTIME, ENDTIME);

CREATE TABLE MDM.OPENINGTIMES_OVERRIDE (
  STATIONID VARCHAR(40) NOT NULL,
  OVERRIDE_TYPE VARCHAR(40) NOT NULL,
  STARTOFPERIOD TIMESTAMP NOT NULL,
  ENDOFPERIOD TIMESTAMP NOT NULL);

CREATE INDEX IX_OPENINGTIMES_OVERRIDE_1 ON MDM.OPENINGTIMES_OVERRIDE (StationId);


/* Tabelle COMPLAINTS */
CREATE TABLE MDM.COMPLAINT (
  ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  STATIONID varchar(40),
  VERSION numeric,
  FROMDATE timestamp,
  COMPLAINTTYPE varchar(30),
  MESSAGE varchar(1000)
);
