apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.adminer.app.servicename }}
  labels:
    name: {{ .Values.adminer.app.servicename }}
    group: db
spec:
  type: ClusterIP
  selector:             # indicates into which pods ClusterIP provides access
    app: adminer
  ports:
    - port: {{ .Values.adminer.app.port }} # port exposed outside ClusterIP
      targetPort: 8080             # port exposed by Pod
