kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.app.pvcName}}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.db.app.storageSize}}
