apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.app.name }}
  labels:
    name: {{ .Values.frontend.app.name }}
spec:
  replicas: {{ .Values.frontend.app.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.frontend.app.name }}
      name: {{ .Values.frontend.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.frontend.app.name }}
        name: {{ .Values.frontend.app.name }}
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: {{ .Values.frontend.app.name }}
        image: {{ .Values.frontend.app.image }}
        imagePullPolicy: {{ .Values.frontend.app.imagePullPolicy }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "256Mi"
            cpu: "300m"
