apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: ingress-{{ .Values.frontend.app.name }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"  # 1 hour
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"     # 1 hour
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"     # 1 hour
  #   ingress.kubernetes.io/ssl-redirect: "false"
  #   nginx.ingress.kubernetes.io/ssl-redirect: "false"
  #   ingress.kubernetes.io/force-ssl-redirect: "false"
  #   nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
  # kubernetes.io/ingress.class: nginx-ingress
  # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  # nginx.ingress.kubernetes.io/proxy-body-size: 100m
  # nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
  # nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  # nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  # nginx.ingress.kubernetes.io/configuration-snippet: |
  #       proxy_set_header X-Forwarded-Proto $scheme;
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.frontend.app.appUrl }}
      http:
        paths:
          - path: /dbviewer
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.adminer.app.servicename }}
                port:
                  number: {{ .Values.adminer.app.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.app.servicename }}
                port:
                  number: {{ .Values.backend.app.port }}
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.app.servicename }}
                port:
                  number: {{ .Values.backend.app.port }}
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ .Values.frontend.app.servicename }}
                port:
                  number: {{ .Values.frontend.app.port }}
